"""Crypto-specific configuration constants."""

CRYPTO_ENABLED = True
CRYPTO_SYMBOLS = ["BTC/USD", "ETH/USD", "SOL/USD", "AVAX/USD", "DOGE/USD", "LINK/USD", "ADA/USD"]
CRYPTO_SCAN_INTERVAL_MINUTES = 15
CRYPTO_MAX_POSITION_PCT = 0.15
CRYPTO_MAX_CONCURRENT = 3
CRYPTO_STOP_LOSS_PCT = 0.05
CRYPTO_TAKE_PROFIT_PCT = 0.15
CRYPTO_TRAILING_STOP_PCT = 0.03
CRYPTO_MIN_SCORE_THRESHOLD = 55
# Scale-out levels
CRYPTO_SCALE_OUT_1_PCT = 0.08   # +8% sell 33%
CRYPTO_SCALE_OUT_2_PCT = 0.15   # +15% sell another 33%
